version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: client-container
    volumes:
      - ./frontend:/app
     
    ports:
      - "5020:5020"
    command: npm start

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: server-container
    volumes:
      - ./server:/app
    ports:
      - "5000:5000"
    command: python api.py
  